In [2]:
import pandas as pd
import numpy as np

In [3]:
demo_df=pd.read_csv("patient_demographics.csv")
demo_df

,patient_id,age_band,gender,state,insurance_type,distance_to_cvs_miles
0,PAT000001,65-74,F,PA,Commercial,0.2
1,PAT000002,18-34,M,MI,Medicaid,1.0
2,PAT000003,50-64,F,FL,Medicare Advantage,0.4
3,PAT000004,50-64,F,CA,Commercial,4.3
4,PAT000005,65-74,M,GA,Medicare,2.5
...,...,...,...,...,...,...
2995,PAT002996,65-74,M,TX,Medicare,1.4
2996,PAT002997,35-49,F,TX,Medicare Advantage,0.3
2997,PAT002998,18-34,M,IL,Commercial,3.4
2998,PAT002999,50-64,F,MI,Medicare,0.7
2999,PAT003000,50-64,F,TX,Commercial,4.2

In [4]:
df=demo_df.copy(deep=True)
df

,patient_id,age_band,gender,state,insurance_type,distance_to_cvs_miles
0,PAT000001,65-74,F,PA,Commercial,0.2
1,PAT000002,18-34,M,MI,Medicaid,1.0
2,PAT000003,50-64,F,FL,Medicare Advantage,0.4
3,PAT000004,50-64,F,CA,Commercial,4.3
4,PAT000005,65-74,M,GA,Medicare,2.5
...,...,...,...,...,...,...
2995,PAT002996,65-74,M,TX,Medicare,1.4
2996,PAT002997,35-49,F,TX,Medicare Advantage,0.3
2997,PAT002998,18-34,M,IL,Commercial,3.4
2998,PAT002999,50-64,F,MI,Medicare,0.7
2999,PAT003000,50-64,F,TX,Commercial,4.2

In [5]:
main_df=pd.read_csv('feature_engineered_df.csv')
main_df

,patient_id,avg_refill_gap,max_refill_gap,tot_late_refill,tot_count_refill_gap,late_refill_per,total_observation_days,unique_covered_days,pdc,days_supply,CMA,CMG,recent_refill_gap
0,PAT000001,3.571429,18.0,10,17,58.823529,388,380,0.979381,750,1.932990,0.020619,8.0
1,PAT000002,3.214286,18.0,7,16,43.750000,837,804,0.960573,1020,1.218638,0.039427,7.0
2,PAT000004,7.533333,24.0,7,14,50.000000,866,834,0.963048,1260,1.454965,0.036952,4.0
3,PAT000005,12.300000,24.0,8,10,80.000000,1014,891,0.878698,900,0.887574,0.121302,0.0
4,PAT000006,3.800000,24.0,4,6,66.666667,488,450,0.922131,480,0.983607,0.077869,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2905,PAT002996,0.666667,4.0,1,6,16.666667,183,179,0.978142,180,0.983607,0.021858,0.0
2906,PAT002997,2.083333,11.0,4,11,36.363636,537,535,0.996276,690,1.284916,0.003724,0.0
2907,PAT002998,7.119048,26.0,8,12,66.666667,691,651,0.942113,960,1.389291,0.057887,19.0
2908,PAT002999,2.166667,8.0,3,6,50.000000,188,175,0.930851,180,0.957447,0.069149,8.0
2909,PAT003000,10.333333,26.0,2,3,66.666667,301,270,0.897010,270,0.897010,0.102990,26.0

In [6]:
df=df[df['patient_id'].isin(main_df['patient_id'])]
df

,patient_id,age_band,gender,state,insurance_type,distance_to_cvs_miles
0,PAT000001,65-74,F,PA,Commercial,0.2
1,PAT000002,18-34,M,MI,Medicaid,1.0
3,PAT000004,50-64,F,CA,Commercial,4.3
4,PAT000005,65-74,M,GA,Medicare,2.5
5,PAT000006,50-64,M,NY,Commercial,4.0
...,...,...,...,...,...,...
2995,PAT002996,65-74,M,TX,Medicare,1.4
2996,PAT002997,35-49,F,TX,Medicare Advantage,0.3
2997,PAT002998,18-34,M,IL,Commercial,3.4
2998,PAT002999,50-64,F,MI,Medicare,0.7
2999,PAT003000,50-64,F,TX,Commercial,4.2

In [7]:
df['age_band'].value_counts()

age_band
50-64    869
65-74    724
35-49    608
75+      413
18-34    296
Name: count, dtype: int64

In [8]:
df=pd.get_dummies(df,columns=['age_band'],drop_first=True,dtype=int)

In [9]:
df['insurance_type'].value_counts()

insurance_type
Commercial            1088
Medicare               840
Medicaid               452
Medicare Advantage     385
Uninsured              145
Name: count, dtype: int64

In [10]:
df=pd.get_dummies(df,columns=['insurance_type'],drop_first=True,dtype=int)

In [11]:
df

,patient_id,gender,state,distance_to_cvs_miles,age_band_35-49,age_band_50-64,age_band_65-74,age_band_75+,insurance_type_Medicaid,insurance_type_Medicare,insurance_type_Medicare Advantage,insurance_type_Uninsured
0,PAT000001,F,PA,0.2,0,0,1,0,0,0,0,0
1,PAT000002,M,MI,1.0,0,0,0,0,1,0,0,0
3,PAT000004,F,CA,4.3,0,1,0,0,0,0,0,0
4,PAT000005,M,GA,2.5,0,0,1,0,0,1,0,0
5,PAT000006,M,NY,4.0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2995,PAT002996,M,TX,1.4,0,0,1,0,0,1,0,0
2996,PAT002997,F,TX,0.3,1,0,0,0,0,0,1,0
2997,PAT002998,M,IL,3.4,0,0,0,0,0,0,0,0
2998,PAT002999,F,MI,0.7,0,1,0,0,0,1,0,0
2999,PAT003000,F,TX,4.2,0,1,0,0,0,0,0,0

In [12]:
df=pd.get_dummies(df,columns=['gender'],drop_first=True,dtype=int)
df

,patient_id,state,distance_to_cvs_miles,age_band_35-49,age_band_50-64,age_band_65-74,age_band_75+,insurance_type_Medicaid,insurance_type_Medicare,insurance_type_Medicare Advantage,insurance_type_Uninsured,gender_M,gender_U
0,PAT000001,PA,0.2,0,0,1,0,0,0,0,0,0,0
1,PAT000002,MI,1.0,0,0,0,0,1,0,0,0,1,0
3,PAT000004,CA,4.3,0,1,0,0,0,0,0,0,0,0
4,PAT000005,GA,2.5,0,0,1,0,0,1,0,0,1,0
5,PAT000006,NY,4.0,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,PAT002996,TX,1.4,0,0,1,0,0,1,0,0,1,0
2996,PAT002997,TX,0.3,1,0,0,0,0,0,1,0,0,0
2997,PAT002998,IL,3.4,0,0,0,0,0,0,0,0,1,0
2998,PAT002999,MI,0.7,0,1,0,0,0,1,0,0,0,0
2999,PAT003000,TX,4.2,0,1,0,0,0,0,0,0,0,0

In [13]:
df['state'].value_counts()

state
TX    330
MI    311
NC    311
NY    308
OH    291
CA    275
IL    274
PA    270
GA    270
FL    270
Name: count, dtype: int64

In [14]:
df=pd.get_dummies(df,columns=['state'],drop_first=True,dtype=int)
df

,patient_id,distance_to_cvs_miles,age_band_35-49,age_band_50-64,age_band_65-74,age_band_75+,insurance_type_Medicaid,insurance_type_Medicare,insurance_type_Medicare Advantage,insurance_type_Uninsured,...,gender_U,state_FL,state_GA,state_IL,state_MI,state_NC,state_NY,state_OH,state_PA,state_TX
0,PAT000001,0.2,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,PAT000002,1.0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,PAT000004,4.3,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,PAT000005,2.5,0,0,1,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
5,PAT000006,4.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,PAT002996,1.4,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2996,PAT002997,0.3,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
2997,PAT002998,3.4,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2998,PAT002999,0.7,0,1,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
2999,PAT003000,4.2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [15]:
df

,patient_id,distance_to_cvs_miles,age_band_35-49,age_band_50-64,age_band_65-74,age_band_75+,insurance_type_Medicaid,insurance_type_Medicare,insurance_type_Medicare Advantage,insurance_type_Uninsured,...,gender_U,state_FL,state_GA,state_IL,state_MI,state_NC,state_NY,state_OH,state_PA,state_TX
0,PAT000001,0.2,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,PAT000002,1.0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,PAT000004,4.3,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,PAT000005,2.5,0,0,1,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
5,PAT000006,4.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,PAT002996,1.4,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2996,PAT002997,0.3,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
2997,PAT002998,3.4,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2998,PAT002999,0.7,0,1,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
2999,PAT003000,4.2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2910 entries, 0 to 2999
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   patient_id                         2910 non-null   object
 1   distance_to_cvs_miles              2910 non-null   float64
 2   age_band_35-49                     2910 non-null   int64
 3   age_band_50-64                     2910 non-null   int64
 4   age_band_65-74                     2910 non-null   int64
 5   age_band_75+                       2910 non-null   int64
 6   insurance_type_Medicaid            2910 non-null   int64
 7   insurance_type_Medicare            2910 non-null   int64
 8   insurance_type_Medicare Advantage  2910 non-null   int64
 9   insurance_type_Uninsured           2910 non-null   int64
 10  gender_M                           2910 non-null   int64
 11  gender_U                           2910 non-null   int64
 12  state_FL                           2910 non-null   int64
 13  state_GA                           2910 non-null   int64
 14  state_IL                           2910 non-null   int64
 15  state_MI                           2910 non-null   int64
 16  state_NC                           2910 non-null   int64
 17  state_NY                           2910 non-null   int64
 18  state_OH                           2910 non-null   int64
 19  state_PA                           2910 non-null   int64
 20  state_TX                           2910 non-null   int64
dtypes: float64(1), int64(19), object(1)
memory usage: 500.2+ KB

In [19]:
df=df.merge(main_df,on='patient_id',how='inner')
df

,patient_id,distance_to_cvs_miles,age_band_35-49,age_band_50-64,age_band_65-74,age_band_75+,insurance_type_Medicaid,insurance_type_Medicare,insurance_type_Medicare Advantage,insurance_type_Uninsured,...,tot_late_refill,tot_count_refill_gap,late_refill_per,total_observation_days,unique_covered_days,pdc,days_supply,CMA,CMG,recent_refill_gap
0,PAT000001,0.2,0,0,1,0,0,0,0,0,...,10,17,58.823529,388,380,0.979381,750,1.932990,0.020619,8.0
1,PAT000002,1.0,0,0,0,0,1,0,0,0,...,7,16,43.750000,837,804,0.960573,1020,1.218638,0.039427,7.0
2,PAT000004,4.3,0,1,0,0,0,0,0,0,...,7,14,50.000000,866,834,0.963048,1260,1.454965,0.036952,4.0
3,PAT000005,2.5,0,0,1,0,0,1,0,0,...,8,10,80.000000,1014,891,0.878698,900,0.887574,0.121302,0.0
4,PAT000006,4.0,0,1,0,0,0,0,0,0,...,4,6,66.666667,488,450,0.922131,480,0.983607,0.077869,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2905,PAT002996,1.4,0,0,1,0,0,1,0,0,...,1,6,16.666667,183,179,0.978142,180,0.983607,0.021858,0.0
2906,PAT002997,0.3,1,0,0,0,0,0,1,0,...,4,11,36.363636,537,535,0.996276,690,1.284916,0.003724,0.0
2907,PAT002998,3.4,0,0,0,0,0,0,0,0,...,8,12,66.666667,691,651,0.942113,960,1.389291,0.057887,19.0
2908,PAT002999,0.7,0,1,0,0,0,1,0,0,...,3,6,50.000000,188,175,0.930851,180,0.957447,0.069149,8.0
2909,PAT003000,4.2,0,1,0,0,0,0,0,0,...,2,3,66.666667,301,270,0.897010,270,0.897010,0.102990,26.0

In [22]:
df.to_csv('final_df.csv',index=False)